/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <limits.h>
#include <stdint.h>
#define STM_DRIVER_IMPLEMENTATION
#include "Nucleo_Driver.h"


int main(void)
{
    /* Loop forever */
	initialiseMCU();

    pinMode(A5, OUTPUT);
    digitalWrite(A5, HIGH);
    for(int i = 0; i < 5000000; i++);

    digitalWrite(A5, LOW);

    Serial.begin(9600);
    
    while(1)
    {
        Serial.println("Hello World!");
    }
}
