/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <sys/errno.h>
#define STM_DRIVER_IMPLEMENTATION
#include "Nucleo_Driver.h"

#define E_COMPASS_ADDR (0x1D << 1)

int main(void)
{
    // Setup
	initialiseMCU();
    Serial.begin(9600);
    
    pinMode(A5, ANALOG);
  //  pinMode(D5, ANALOG);
  //  pinMode(D6, ANALOG);
   // pinMode(D9, ANALOG);
   // pinMode(D10, ANALOG);
   // pinMode(D11, ANALOG);
    u16 raw_data = 0;
    
    
    /* Loop forever */
    while(1)
    {
        raw_data = analogRead(A5);
        Serial.print("Measured Voltage: ");
        Serial.println_int(raw_data);
        delay(500);
    }
}
